{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gwi.fullname" . }}-api
  labels:
    {{- include "gwi.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "gwi.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "gwi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
          env:
            - name: ORCHESTRATOR
              value: {{ .Values.api.env.ORCHESTRATOR | quote }}
            - name: SECRET_SCAN_MODE
              value: {{ .Values.api.env.SECRET_SCAN_MODE | quote }}
{{- end }}
